-- Seed de regiones/comunas de Chile (regions_comunas)
-- Generado a partir de scripts/seed_regions_comunas.py -- validar contra la division oficial INE/SUBDERE.

INSERT INTO regions_comunas (id, region, comuna) VALUES
    (gen_random_uuid(), 'Arica y Parinacota', 'Arica'),
    (gen_random_uuid(), 'Arica y Parinacota', 'Camarones'),
    (gen_random_uuid(), 'Arica y Parinacota', 'Putre'),
    (gen_random_uuid(), 'Arica y Parinacota', 'General Lagos'),
    (gen_random_uuid(), 'Tarapacá', 'Iquique'),
    (gen_random_uuid(), 'Tarapacá', 'Alto Hospicio'),
    (gen_random_uuid(), 'Tarapacá', 'Pozo Almonte'),
    (gen_random_uuid(), 'Tarapacá', 'Camiña'),
    (gen_random_uuid(), 'Tarapacá', 'Colchane'),
    (gen_random_uuid(), 'Tarapacá', 'Huara'),
    (gen_random_uuid(), 'Tarapacá', 'Pica'),
    (gen_random_uuid(), 'Antofagasta', 'Antofagasta'),
    (gen_random_uuid(), 'Antofagasta', 'Mejillones'),
    (gen_random_uuid(), 'Antofagasta', 'Sierra Gorda'),
    (gen_random_uuid(), 'Antofagasta', 'Taltal'),
    (gen_random_uuid(), 'Antofagasta', 'Calama'),
    (gen_random_uuid(), 'Antofagasta', 'Ollagüe'),
    (gen_random_uuid(), 'Antofagasta', 'San Pedro de Atacama'),
    (gen_random_uuid(), 'Antofagasta', 'Tocopilla'),
    (gen_random_uuid(), 'Antofagasta', 'María Elena'),
    (gen_random_uuid(), 'Atacama', 'Copiapó'),
    (gen_random_uuid(), 'Atacama', 'Caldera'),
    (gen_random_uuid(), 'Atacama', 'Tierra Amarilla'),
    (gen_random_uuid(), 'Atacama', 'Chañaral'),
    (gen_random_uuid(), 'Atacama', 'Diego de Almagro'),
    (gen_random_uuid(), 'Atacama', 'Vallenar'),
    (gen_random_uuid(), 'Atacama', 'Alto del Carmen'),
    (gen_random_uuid(), 'Atacama', 'Freirina'),
    (gen_random_uuid(), 'Atacama', 'Huasco'),
    (gen_random_uuid(), 'Coquimbo', 'La Serena'),
    (gen_random_uuid(), 'Coquimbo', 'Coquimbo'),
    (gen_random_uuid(), 'Coquimbo', 'Andacollo'),
    (gen_random_uuid(), 'Coquimbo', 'La Higuera'),
    (gen_random_uuid(), 'Coquimbo', 'Paihuano'),
    (gen_random_uuid(), 'Coquimbo', 'Vicuña'),
    (gen_random_uuid(), 'Coquimbo', 'Illapel'),
    (gen_random_uuid(), 'Coquimbo', 'Canela'),
    (gen_random_uuid(), 'Coquimbo', 'Los Vilos'),
    (gen_random_uuid(), 'Coquimbo', 'Salamanca'),
    (gen_random_uuid(), 'Coquimbo', 'Ovalle'),
    (gen_random_uuid(), 'Coquimbo', 'Combarbalá'),
    (gen_random_uuid(), 'Coquimbo', 'Monte Patria'),
    (gen_random_uuid(), 'Coquimbo', 'Punitaqui'),
    (gen_random_uuid(), 'Coquimbo', 'Río Hurtado'),
    (gen_random_uuid(), 'Valparaíso', 'Valparaíso'),
    (gen_random_uuid(), 'Valparaíso', 'Casablanca'),
    (gen_random_uuid(), 'Valparaíso', 'Concón'),
    (gen_random_uuid(), 'Valparaíso', 'Juan Fernández'),
    (gen_random_uuid(), 'Valparaíso', 'Puchuncaví'),
    (gen_random_uuid(), 'Valparaíso', 'Quintero'),
    (gen_random_uuid(), 'Valparaíso', 'Viña del Mar'),
    (gen_random_uuid(), 'Valparaíso', 'Isla de Pascua'),
    (gen_random_uuid(), 'Valparaíso', 'Los Andes'),
    (gen_random_uuid(), 'Valparaíso', 'Calle Larga'),
    (gen_random_uuid(), 'Valparaíso', 'Rinconada'),
    (gen_random_uuid(), 'Valparaíso', 'San Esteban'),
    (gen_random_uuid(), 'Valparaíso', 'La Ligua'),
    (gen_random_uuid(), 'Valparaíso', 'Cabildo'),
    (gen_random_uuid(), 'Valparaíso', 'Papudo'),
    (gen_random_uuid(), 'Valparaíso', 'Petorca'),
    (gen_random_uuid(), 'Valparaíso', 'Zapallar'),
    (gen_random_uuid(), 'Valparaíso', 'Quillota'),
    (gen_random_uuid(), 'Valparaíso', 'Calera'),
    (gen_random_uuid(), 'Valparaíso', 'Hijuelas'),
    (gen_random_uuid(), 'Valparaíso', 'La Cruz'),
    (gen_random_uuid(), 'Valparaíso', 'Nogales'),
    (gen_random_uuid(), 'Valparaíso', 'San Antonio'),
    (gen_random_uuid(), 'Valparaíso', 'Algarrobo'),
    (gen_random_uuid(), 'Valparaíso', 'Cartagena'),
    (gen_random_uuid(), 'Valparaíso', 'El Quisco'),
    (gen_random_uuid(), 'Valparaíso', 'El Tabo'),
    (gen_random_uuid(), 'Valparaíso', 'Santo Domingo'),
    (gen_random_uuid(), 'Valparaíso', 'San Felipe'),
    (gen_random_uuid(), 'Valparaíso', 'Catemu'),
    (gen_random_uuid(), 'Valparaíso', 'Llaillay'),
    (gen_random_uuid(), 'Valparaíso', 'Panquehue'),
    (gen_random_uuid(), 'Valparaíso', 'Putaendo'),
    (gen_random_uuid(), 'Valparaíso', 'Santa María'),
    (gen_random_uuid(), 'Valparaíso', 'Limache'),
    (gen_random_uuid(), 'Valparaíso', 'Olmué'),
    (gen_random_uuid(), 'Valparaíso', 'Villa Alemana'),
    (gen_random_uuid(), 'Valparaíso', 'Quilpué'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Santiago'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Cerrillos'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Cerro Navia'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Conchalí'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'El Bosque'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Estación Central'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Huechuraba'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Independencia'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'La Cisterna'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'La Florida'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'La Granja'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'La Pintana'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'La Reina'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Las Condes'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Lo Barnechea'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Lo Espejo'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Lo Prado'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Macul'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Maipú'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Ñuñoa'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Pedro Aguirre Cerda'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Peñalolén'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Providencia'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Pudahuel'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Quilicura'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Quinta Normal'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Recoleta'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Renca'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San Joaquín'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San Miguel'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San Ramón'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Vitacura'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Puente Alto'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Pirque'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San José de Maipo'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Colina'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Lampa'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Til Til'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San Bernardo'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Buin'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Calera de Tango'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Paine'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Melipilla'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Alhué'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Curacaví'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'María Pinto'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'San Pedro'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Talagante'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'El Monte'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Isla de Maipo'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Padre Hurtado'),
    (gen_random_uuid(), 'Metropolitana de Santiago', 'Peñaflor'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Rancagua'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Codegua'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Coinco'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Coltauco'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Doñihue'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Graneros'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Las Cabras'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Machalí'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Malloa'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Mostazal'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Olivar'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Peumo'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Pichidegua'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Quinta de Tilcoco'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Rengo'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Requínoa'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'San Vicente'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Pichilemu'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'La Estrella'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Litueche'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Marchihue'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Navidad'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Paredones'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'San Fernando'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Chépica'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Chimbarongo'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Lolol'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Nancagua'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Palmilla'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Peralillo'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Placilla'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Pumanque'),
    (gen_random_uuid(), 'Libertador General Bernardo O''Higgins', 'Santa Cruz'),
    (gen_random_uuid(), 'Maule', 'Talca'),
    (gen_random_uuid(), 'Maule', 'Constitución'),
    (gen_random_uuid(), 'Maule', 'Curepto'),
    (gen_random_uuid(), 'Maule', 'Empedrado'),
    (gen_random_uuid(), 'Maule', 'Maule'),
    (gen_random_uuid(), 'Maule', 'Pelarco'),
    (gen_random_uuid(), 'Maule', 'Pencahue'),
    (gen_random_uuid(), 'Maule', 'Río Claro'),
    (gen_random_uuid(), 'Maule', 'San Clemente'),
    (gen_random_uuid(), 'Maule', 'San Rafael'),
    (gen_random_uuid(), 'Maule', 'Cauquenes'),
    (gen_random_uuid(), 'Maule', 'Chanco'),
    (gen_random_uuid(), 'Maule', 'Pelluhue'),
    (gen_random_uuid(), 'Maule', 'Curicó'),
    (gen_random_uuid(), 'Maule', 'Hualañé'),
    (gen_random_uuid(), 'Maule', 'Licantén'),
    (gen_random_uuid(), 'Maule', 'Molina'),
    (gen_random_uuid(), 'Maule', 'Rauco'),
    (gen_random_uuid(), 'Maule', 'Romeral'),
    (gen_random_uuid(), 'Maule', 'Sagrada Familia'),
    (gen_random_uuid(), 'Maule', 'Teno'),
    (gen_random_uuid(), 'Maule', 'Vichuquén'),
    (gen_random_uuid(), 'Maule', 'Linares'),
    (gen_random_uuid(), 'Maule', 'Colbún'),
    (gen_random_uuid(), 'Maule', 'Longaví'),
    (gen_random_uuid(), 'Maule', 'Parral'),
    (gen_random_uuid(), 'Maule', 'Retiro'),
    (gen_random_uuid(), 'Maule', 'San Javier'),
    (gen_random_uuid(), 'Maule', 'Villa Alegre'),
    (gen_random_uuid(), 'Maule', 'Yerbas Buenas'),
    (gen_random_uuid(), 'Ñuble', 'Chillán'),
    (gen_random_uuid(), 'Ñuble', 'Bulnes'),
    (gen_random_uuid(), 'Ñuble', 'Chillán Viejo'),
    (gen_random_uuid(), 'Ñuble', 'El Carmen'),
    (gen_random_uuid(), 'Ñuble', 'Pemuco'),
    (gen_random_uuid(), 'Ñuble', 'Pinto'),
    (gen_random_uuid(), 'Ñuble', 'Quillón'),
    (gen_random_uuid(), 'Ñuble', 'San Ignacio'),
    (gen_random_uuid(), 'Ñuble', 'Yungay'),
    (gen_random_uuid(), 'Ñuble', 'Cobquecura'),
    (gen_random_uuid(), 'Ñuble', 'Coelemu'),
    (gen_random_uuid(), 'Ñuble', 'Ninhue'),
    (gen_random_uuid(), 'Ñuble', 'Portezuelo'),
    (gen_random_uuid(), 'Ñuble', 'Quirihue'),
    (gen_random_uuid(), 'Ñuble', 'Ránquil'),
    (gen_random_uuid(), 'Ñuble', 'Treguaco'),
    (gen_random_uuid(), 'Ñuble', 'San Carlos'),
    (gen_random_uuid(), 'Ñuble', 'Coihueco'),
    (gen_random_uuid(), 'Ñuble', 'Ñiquén'),
    (gen_random_uuid(), 'Ñuble', 'San Fabián'),
    (gen_random_uuid(), 'Ñuble', 'San Nicolás'),
    (gen_random_uuid(), 'Biobío', 'Concepción'),
    (gen_random_uuid(), 'Biobío', 'Coronel'),
    (gen_random_uuid(), 'Biobío', 'Chiguayante'),
    (gen_random_uuid(), 'Biobío', 'Florida'),
    (gen_random_uuid(), 'Biobío', 'Hualqui'),
    (gen_random_uuid(), 'Biobío', 'Lota'),
    (gen_random_uuid(), 'Biobío', 'Penco'),
    (gen_random_uuid(), 'Biobío', 'San Pedro de la Paz'),
    (gen_random_uuid(), 'Biobío', 'Santa Juana'),
    (gen_random_uuid(), 'Biobío', 'Talcahuano'),
    (gen_random_uuid(), 'Biobío', 'Tomé'),
    (gen_random_uuid(), 'Biobío', 'Hualpén'),
    (gen_random_uuid(), 'Biobío', 'Lebu'),
    (gen_random_uuid(), 'Biobío', 'Arauco'),
    (gen_random_uuid(), 'Biobío', 'Cañete'),
    (gen_random_uuid(), 'Biobío', 'Contulmo'),
    (gen_random_uuid(), 'Biobío', 'Curanilahue'),
    (gen_random_uuid(), 'Biobío', 'Los Álamos'),
    (gen_random_uuid(), 'Biobío', 'Tirúa'),
    (gen_random_uuid(), 'Biobío', 'Los Ángeles'),
    (gen_random_uuid(), 'Biobío', 'Antuco'),
    (gen_random_uuid(), 'Biobío', 'Cabrero'),
    (gen_random_uuid(), 'Biobío', 'Laja'),
    (gen_random_uuid(), 'Biobío', 'Mulchén'),
    (gen_random_uuid(), 'Biobío', 'Nacimiento'),
    (gen_random_uuid(), 'Biobío', 'Negrete'),
    (gen_random_uuid(), 'Biobío', 'Quilaco'),
    (gen_random_uuid(), 'Biobío', 'Quilleco'),
    (gen_random_uuid(), 'Biobío', 'San Rosendo'),
    (gen_random_uuid(), 'Biobío', 'Santa Bárbara'),
    (gen_random_uuid(), 'Biobío', 'Tucapel'),
    (gen_random_uuid(), 'Biobío', 'Yumbel'),
    (gen_random_uuid(), 'Biobío', 'Alto Biobío'),
    (gen_random_uuid(), 'La Araucanía', 'Temuco'),
    (gen_random_uuid(), 'La Araucanía', 'Carahue'),
    (gen_random_uuid(), 'La Araucanía', 'Cunco'),
    (gen_random_uuid(), 'La Araucanía', 'Curarrehue'),
    (gen_random_uuid(), 'La Araucanía', 'Freire'),
    (gen_random_uuid(), 'La Araucanía', 'Galvarino'),
    (gen_random_uuid(), 'La Araucanía', 'Gorbea'),
    (gen_random_uuid(), 'La Araucanía', 'Lautaro'),
    (gen_random_uuid(), 'La Araucanía', 'Loncoche'),
    (gen_random_uuid(), 'La Araucanía', 'Melipeuco'),
    (gen_random_uuid(), 'La Araucanía', 'Nueva Imperial'),
    (gen_random_uuid(), 'La Araucanía', 'Padre Las Casas'),
    (gen_random_uuid(), 'La Araucanía', 'Perquenco'),
    (gen_random_uuid(), 'La Araucanía', 'Pitrufquén'),
    (gen_random_uuid(), 'La Araucanía', 'Pucón'),
    (gen_random_uuid(), 'La Araucanía', 'Saavedra'),
    (gen_random_uuid(), 'La Araucanía', 'Teodoro Schmidt'),
    (gen_random_uuid(), 'La Araucanía', 'Toltén'),
    (gen_random_uuid(), 'La Araucanía', 'Vilcún'),
    (gen_random_uuid(), 'La Araucanía', 'Villarrica'),
    (gen_random_uuid(), 'La Araucanía', 'Cholchol'),
    (gen_random_uuid(), 'La Araucanía', 'Angol'),
    (gen_random_uuid(), 'La Araucanía', 'Collipulli'),
    (gen_random_uuid(), 'La Araucanía', 'Curacautín'),
    (gen_random_uuid(), 'La Araucanía', 'Ercilla'),
    (gen_random_uuid(), 'La Araucanía', 'Lonquimay'),
    (gen_random_uuid(), 'La Araucanía', 'Los Sauces'),
    (gen_random_uuid(), 'La Araucanía', 'Lumaco'),
    (gen_random_uuid(), 'La Araucanía', 'Purén'),
    (gen_random_uuid(), 'La Araucanía', 'Renaico'),
    (gen_random_uuid(), 'La Araucanía', 'Traiguén'),
    (gen_random_uuid(), 'La Araucanía', 'Victoria'),
    (gen_random_uuid(), 'Los Ríos', 'Valdivia'),
    (gen_random_uuid(), 'Los Ríos', 'Corral'),
    (gen_random_uuid(), 'Los Ríos', 'Lanco'),
    (gen_random_uuid(), 'Los Ríos', 'Los Lagos'),
    (gen_random_uuid(), 'Los Ríos', 'Máfil'),
    (gen_random_uuid(), 'Los Ríos', 'Mariquina'),
    (gen_random_uuid(), 'Los Ríos', 'Paillaco'),
    (gen_random_uuid(), 'Los Ríos', 'Panguipulli'),
    (gen_random_uuid(), 'Los Ríos', 'La Unión'),
    (gen_random_uuid(), 'Los Ríos', 'Futrono'),
    (gen_random_uuid(), 'Los Ríos', 'Lago Ranco'),
    (gen_random_uuid(), 'Los Ríos', 'Río Bueno'),
    (gen_random_uuid(), 'Los Lagos', 'Puerto Montt'),
    (gen_random_uuid(), 'Los Lagos', 'Calbuco'),
    (gen_random_uuid(), 'Los Lagos', 'Cochamó'),
    (gen_random_uuid(), 'Los Lagos', 'Fresia'),
    (gen_random_uuid(), 'Los Lagos', 'Frutillar'),
    (gen_random_uuid(), 'Los Lagos', 'Los Muermos'),
    (gen_random_uuid(), 'Los Lagos', 'Llanquihue'),
    (gen_random_uuid(), 'Los Lagos', 'Maullín'),
    (gen_random_uuid(), 'Los Lagos', 'Puerto Varas'),
    (gen_random_uuid(), 'Los Lagos', 'Castro'),
    (gen_random_uuid(), 'Los Lagos', 'Ancud'),
    (gen_random_uuid(), 'Los Lagos', 'Chonchi'),
    (gen_random_uuid(), 'Los Lagos', 'Curaco de Vélez'),
    (gen_random_uuid(), 'Los Lagos', 'Dalcahue'),
    (gen_random_uuid(), 'Los Lagos', 'Puqueldón'),
    (gen_random_uuid(), 'Los Lagos', 'Queilén'),
    (gen_random_uuid(), 'Los Lagos', 'Quellón'),
    (gen_random_uuid(), 'Los Lagos', 'Quemchi'),
    (gen_random_uuid(), 'Los Lagos', 'Quinchao'),
    (gen_random_uuid(), 'Los Lagos', 'Osorno'),
    (gen_random_uuid(), 'Los Lagos', 'Puerto Octay'),
    (gen_random_uuid(), 'Los Lagos', 'Purranque'),
    (gen_random_uuid(), 'Los Lagos', 'Puyehue'),
    (gen_random_uuid(), 'Los Lagos', 'Río Negro'),
    (gen_random_uuid(), 'Los Lagos', 'San Juan de la Costa'),
    (gen_random_uuid(), 'Los Lagos', 'San Pablo'),
    (gen_random_uuid(), 'Los Lagos', 'Chaitén'),
    (gen_random_uuid(), 'Los Lagos', 'Futaleufú'),
    (gen_random_uuid(), 'Los Lagos', 'Hualaihué'),
    (gen_random_uuid(), 'Los Lagos', 'Palena'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Coyhaique'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Lago Verde'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Aysén'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Cisnes'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Guaitecas'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Cochrane'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'O''Higgins'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Tortel'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Chile Chico'),
    (gen_random_uuid(), 'Aysén del General Carlos Ibáñez del Campo', 'Río Ibáñez'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Punta Arenas'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Laguna Blanca'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Río Verde'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'San Gregorio'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Cabo de Hornos'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Antártica'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Porvenir'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Primavera'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Timaukel'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Natales'),
    (gen_random_uuid(), 'Magallanes y de la Antártica Chilena', 'Torres del Paine')
ON CONFLICT ON CONSTRAINT uq_region_comuna DO NOTHING;
